### ISSUE TITLE
'Invalid action' and 'Handle Not Available' in IonicAuthorizationRequestHandler

### ISSUE THREAD

**Issue by govertbuijs** [wi3land/ionic-appauth#10]
Hi,

I've tried both the Okta example (both from blog and the Github version) and your ionic-appauth-ng-demo.
In the browser they both work with multiple OIDC providers. 
Unfortunately, when i try the examples on Android (both emulator and device) the above errors appear. 

Do you have any pointers how to tackle this? I've tried updating to the latest version (0.4.4) instead of 0.3.9, but that didn't change anything.

**Comment by govertbuijs** [comment]
To answer my own question : this is fixed by setting the Android launchmode to 'singleTask' instead of the default 'singleTop'.
For this you need to add '<preference name="AndroidLaunchMode" value="singleTask" />' to config.xml.

**Comment by PowerMogli** [comment]
> I do this change `<preference name="AndroidLaunchMode" value="singleTask" />`, but the same error persist to occur.

It is the same for me in our ionic app
