### ISSUE TITLE
[Android] Bad redirect after login in Azure AD (only using Intune Company Portal)

### ISSUE THREAD

**Issue by bartdeveloper** [wi3land/ionic-appauth#11]
Hi,
On Android device when app is run from Intune Company Portal (it's Microsoft service for managing devices) after login to Azure AD I got bad redirect with error "ERR_UNKNOWN_URL_SCHEME".
It issue occurs only when app is run from Intune Company Portal (Managed Google Play store). It not occurs on iOS and when I download app from Google Play store market.
I'm using cordova-plugin-customurlscheme 4.4.0 with correct value.
![Screenshot_20191217-120743](https://user-images.githubusercontent.com/44911371/70990542-0fdd5b80-20c6-11ea-90bc-705e94c8c32e.jpg)

What might cause a issue?

**Comment by wi3land** [comment]
I would say the issue is probably that you haven't white labelled your redirect url in azure. That is just a guess though.

**Comment by bartdeveloper** [comment]
Redirect uri is correct white labelled in Azure (as I mentioned - when app is installed from Google play store then always all work). Issue is related to chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=181186
