### ISSUE TITLE
Capacitor Ionic App Auth Demo

### ISSUE THREAD

**Issue by teenahjob** [wi3land/ionic-appauth#127]
Hello,
The demo for the angular capacitor is working on Chrome with the Okta Dev account.
But it does not work when I try to open it with IOS simulator. It redirects to Okta login, and shows the login page, when it tries to redirect to the app, it throws an error "Safari could not open the web page"
Can you please help debug?

**Comment by mraible** [comment]
Did you add your custom scheme to `ios/App/App/Info.plist`:

```xml
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleURLName</key>
    <string>com.getcapacitor.capacitor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>capacitor</string>
      <string>com.okta.dev-133337</string>
    </array>
  </dict>
</array>
```

https://github.com/oktadev/schematics#ios

**Comment by mraible** [comment]
Closing because no response.

**Comment by univalchemist** [comment]
I can not get the demo app up on the iOS simulator. It does not open the okta web page even.

**Comment by mraible** [comment]
Which demo are you using? I tried the Angular + Capacitor one a couple of weeks ago and didn't have any issues with Okta or Auth0.

https://github.com/wi3land/ionic-appauth/tree/master/demos/angular-capacitor

**Comment by univalchemist** [comment]
Yes, I have been trying it right now. It works fine on browser by `ionic serve` but does not on iOS simulator

**Comment by univalchemist** [comment]
I am attaching screenshot of error when I click sign in
![image](https://user-images.githubusercontent.com/40210815/191085292-141ed506-626b-421c-b526-2841102a3a5b.png)

**Comment by mraible** [comment]
Are you using Okta or some other identity provider? If Okta, do you have a developer account or a workforce account?

**Comment by univalchemist** [comment]
I am using okta and have an account but not sure what kind of account. Anyways, it does work fine on browser but not on iOS Simulator.

**Comment by univalchemist** [comment]
I think it is a developer account.

**Comment by univalchemist** [comment]
> To Native ->  Http request 62360100
2022-09-20 02:22:20.615144+0800 App[19223:422518] [boringssl] boringssl_metrics_log_metric_block_invoke(153) Failed to log metrics
2022-09-20 02:22:21.106625+0800 App[19223:422549] [NSURLSession sharedSession] may not be invalidated
⚡️  TO JS {"headers":{"Server":"nginx","x-okta-request-id":"YyizXQE4LkgMkT6l7zxq0AAADDM","Date":"Mon, 19 Sep 2022 18:22:21 GMT","Strict-Transport-Security":"max-age=315360000; includeSubDomains","content-security-policy":"default-src 'self' dev-8375994.okta.com *.ok
⚡️  [error] - ERROR {"rejection":{"code":"UNIMPLEMENTED"},"promise":{"__zone_symbol__state":0,"__zone_symbol__value":"..."},"zone":{"_parent":{"_parent":null,"_name":"<root>","_properties":{},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":0},"zone":"...","_parentDelegate":null,"_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":null,"_invokeDlgt":null,"_invokeCurrZone":null,"_handleErrorZS":null,"_handleErrorDlgt":null,"_handleErrorCurrZone":null,"_scheduleTaskZS":null,"_scheduleTaskDlgt":null,"_scheduleTaskCurrZone":null,"_invokeTaskZS":null,"_invokeTaskDlgt":null,"_invokeTaskCurrZone":null,"_cancelTaskZS":null,"_cancelTaskDlgt":null,"_cancelTaskCurrZone":null,"_hasTaskZS":null,"_hasTaskDlgt":null,"_hasTaskDlgtOwner":null,"_hasTaskCurrZone":null}},"_name":"angular","_properties":{"isAngularZone":true},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":10},"zone":"...","_parentDelegate":"...","_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":{"name":"angular","properties":"..."},"_invokeDlgt":"...","_invokeCurrZone":"...","_handleErrorZS":"...","_handleErrorDlgt":"...","_handleErrorCurrZone":"...","_scheduleTaskZS":{"name":""},"_scheduleTaskDlgt":"...","_scheduleTaskCurrZone":"...","_invokeTaskZS":"...","_invokeTaskDlgt":"...","_invokeTaskCurrZone":"...","_cancelTaskZS":"...","_cancelTaskDlgt":"...","_cancelTaskCurrZone":"...","_hasTaskZS":"...","_hasTaskDlgt":"...","_hasTaskDlgtOwner":"...","_hasTaskCurrZone":"..."}},"task":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","runCount":0}}
⚡️  [error] - ERROR {"rejection":{"code":"UNIMPLEMENTED"},"promise":{"__zone_symbol__state":0,"__zone_symbol__value":"..."},"zone":{"_parent":{"_parent":null,"_name":"<root>","_properties":{},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":0},"zone":"...","_parentDelegate":null,"_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":null,"_invokeDlgt":null,"_invokeCurrZone":null,"_handleErrorZS":null,"_handleErrorDlgt":null,"_handleErrorCurrZone":null,"_scheduleTaskZS":null,"_scheduleTaskDlgt":null,"_scheduleTaskCurrZone":null,"_invokeTaskZS":null,"_invokeTaskDlgt":null,"_invokeTaskCurrZone":null,"_cancelTaskZS":null,"_cancelTaskDlgt":null,"_cancelTaskCurrZone":null,"_hasTaskZS":null,"_hasTaskDlgt":null,"_hasTaskDlgtOwner":null,"_hasTaskCurrZone":null}},"_name":"angular","_properties":{"isAngularZone":true},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":10},"zone":"...","_parentDelegate":"...","_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":{"name":"angular","properties":"..."},"_invokeDlgt":"...","_invokeCurrZone":"...","_handleErrorZS":"...","_handleErrorDlgt":"...","_handleErrorCurrZone":"...","_scheduleTaskZS":{"name":""},"_scheduleTaskDlgt":"...","_scheduleTaskCurrZone":"...","_invokeTaskZS":"...","_invokeTaskDlgt":"...","_invokeTaskCurrZone":"...","_cancelTaskZS":"...","_cancelTaskDlgt":"...","_cancelTaskCurrZone":"...","_hasTaskZS":"...","_hasTaskDlgt":"...","_hasTaskDlgtOwner":"...","_hasTaskCurrZone":"..."}},"task":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","runCount":0}}
⚡️  [error] - ERROR {"rejection":{"code":"UNIMPLEMENTED"},"promise":{"__zone_symbol__state":0,"__zone_symbol__value":"..."},"zone":{"_parent":{"_parent":null,"_name":"<root>","_properties":{},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":0},"zone":"...","_parentDelegate":null,"_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":null,"_invokeDlgt":null,"_invokeCurrZone":null,"_handleErrorZS":null,"_handleErrorDlgt":null,"_handleErrorCurrZone":null,"_scheduleTaskZS":null,"_scheduleTaskDlgt":null,"_scheduleTaskCurrZone":null,"_invokeTaskZS":null,"_invokeTaskDlgt":null,"_invokeTaskCurrZone":null,"_cancelTaskZS":null,"_cancelTaskDlgt":null,"_cancelTaskCurrZone":null,"_hasTaskZS":null,"_hasTaskDlgt":null,"_hasTaskDlgtOwner":null,"_hasTaskCurrZone":null}},"_name":"angular","_properties":{"isAngularZone":true},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":10},"zone":"...","_parentDelegate":"...","_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":{"name":"angular","properties":"..."},"_invokeDlgt":"...","_invokeCurrZone":"...","_handleErrorZS":"...","_handleErrorDlgt":"...","_handleErrorCurrZone":"...","_scheduleTaskZS":{"name":""},"_scheduleTaskDlgt":"...","_scheduleTaskCurrZone":"...","_invokeTaskZS":"...","_invokeTaskDlgt":"...","_invokeTaskCurrZone":"...","_cancelTaskZS":"...","_cancelTaskDlgt":"...","_cancelTaskCurrZone":"...","_hasTaskZS":"...","_hasTaskDlgt":"...","_hasTaskDlgtOwner":"...","_hasTaskCurrZone":"..."}},"task":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","runCount":0}}
⚡️  [error] - ERROR {"rejection":{"code":"UNIMPLEMENTED"},"promise":{"__zone_symbol__state":0,"__zone_symbol__value":"..."},"zone":{"_parent":{"_parent":null,"_name":"<root>","_properties":{},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":0},"zone":"...","_parentDelegate":null,"_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":null,"_invokeDlgt":null,"_invokeCurrZone":null,"_handleErrorZS":null,"_handleErrorDlgt":null,"_handleErrorCurrZone":null,"_scheduleTaskZS":null,"_scheduleTaskDlgt":null,"_scheduleTaskCurrZone":null,"_invokeTaskZS":null,"_invokeTaskDlgt":null,"_invokeTaskCurrZone":null,"_cancelTaskZS":null,"_cancelTaskDlgt":null,"_cancelTaskCurrZone":null,"_hasTaskZS":null,"_hasTaskDlgt":null,"_hasTaskDlgtOwner":null,"_hasTaskCurrZone":null}},"_name":"angular","_properties":{"isAngularZone":true},"_zoneDelegate":{"_taskCounts":{"microTask":0,"macroTask":0,"eventTask":10},"zone":"...","_parentDelegate":"...","_forkZS":null,"_forkDlgt":null,"_forkCurrZone":null,"_interceptZS":null,"_interceptDlgt":null,"_interceptCurrZone":null,"_invokeZS":{"name":"angular","properties":"..."},"_invokeDlgt":"...","_invokeCurrZone":"...","_handleErrorZS":"...","_handleErrorDlgt":"...","_handleErrorCurrZone":"...","_scheduleTaskZS":{"name":""},"_scheduleTaskDlgt":"...","_scheduleTaskCurrZone":"...","_invokeTaskZS":"...","_invokeTaskDlgt":"...","_invokeTaskCurrZone":"...","_cancelTaskZS":"...","_cancelTaskDlgt":"...","_cancelTaskCurrZone":"...","_hasTaskZS":"...","_hasTaskDlgt":"...","_hasTaskDlgtOwner":"...","_hasTaskCurrZone":"..."}},"task":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","runCount":0}}

**Comment by univalchemist** [comment]
This is an error when I try to sign in.

**Comment by mraible** [comment]
I'm not sure what the problem could be. You might try using [these instructions](https://github.com/oktadev/schematics/#okta-for-ionic) to configure your app on Okta. You could also email developers@okta.com for support.

**Comment by salesforcecodes** [comment]
I am using Salesforce an Open ID provider. It is working fine in web. But doesn't work in iOS or android simulators/devices. It is not opening the login page. When I click the button to initiate oauth the following message shows up in the logs. Can someone please help?

```
⚡️  To Native ->  CapacitorHttp request 99156329
⚡️  [log] - calling, sign in
⚡️  [log] - calling, sign in
⚡️  To Native ->  CapacitorHttp request 99156330
2023-11-14 15:22:03.089573-0700 App[74442:3737732] [NSURLSession sharedSession] may not be invalidated
⚡️  TO JS {"status":200,"headers":{"Access-Control-Allow-Origin":"*","Transfer-Encoding":"Identity","Content-Encoding":"gzip","Strict-Transport-Security":"max-age=63072000; includeSubDomains","Cache-Control":"no-cache,must-revalidate,max-age=0,no-store,private","Var
2023-11-14 15:22:03.182139-0700 App[74442:3737834] [NSURLSession sharedSession] may not be invalidated
⚡️  TO JS {"url":"https:\/\/salesforce-server-address.com\/.well-known\/openid-configuration","data":{"display_values_supported":["page","popup","touch"],"token_endpoint":"https:\/\/salesforce-server-address.com\/vforcesite\/services\/oauth2\/token",
```
