### ISSUE TITLE
Capacitor V4 compatibility

### ISSUE THREAD

**Issue by richardkshergold** [wi3land/ionic-appauth#128]
I don't think this will be compatible with Capacitor 4 as the @capacitor/storage plugin has been renamed to @capacitor/preferences (the API remains the same)

**Comment by de-dan** [comment]
This package can be made compatible with capacitor 4 as soon as this package `capacitor-secure-storage-plugin` is updated.
I already [created a PR there](https://github.com/martinkasa/capacitor-secure-storage-plugin/pull/59).

**Comment by richardkshergold** [comment]
Thanks for that @de-dan - I'm migrating our app to Capacitor 4 because of the change [announced by Google re the API Limitations](https://news.ionic.io/en/google-play-store-is-updating-api-level-requirements) so presumably I need to wait for both of these libraries to be made V4 Compatible ?

**Comment by richardshergold** [comment]
I think the secure storage plugin PR has now been merged

**Comment by mraible** [comment]
I tried to fix this today but ran into issues. Not sure how to fix it. See https://github.com/wi3land/ionic-appauth/pull/131.

**Comment by mraible** [comment]
I've figured out a fix, now I'm just testing the demos.
