### ISSUE TITLE
Can you provide support for IONIC 5 / Angular 9 ?

### ISSUE THREAD

**Issue by asad77** [wi3land/ionic-appauth#13]
Hello,

I am having issues when migrating to IONIC 5 and Angular 9, can you provide this support please ?

**Comment by wi3land** [comment]
I'll Take the latest tonight and try and see if i can get the ionic-appauth-ng-demo up to ionic 5.
Are you using cordova or capacitor?

**Comment by asad77** [comment]
> I'll Take the latest tonight and try and see if i can get the ionic-appauth-ng-demo up to ionic 5.
> Are you using cordova or capacitor?

I am using capacitor.

**Comment by wi3land** [comment]
I have updated and tested both the angular/capacitor and angular/cordova demos. They are now working. There seems to have been some changes to how the App capacitor plugin worked that was causing the demo to fail. This has now been fixed. 

If this isn't the same as your issue, can you give further information into what is causing you problems.

**Comment by wi3land** [comment]
@asad77 has the example solved your issue, am I free to close this one?

**Comment by asad77** [comment]
@wi3land Thank you very much, it works fine now 👍

**Comment by asad77** [comment]
@wi3land i am sorry but i didn't test on Android device (i only test on WEB).
Since i update to 0.4.6, i am having the issue below :
```
W/Cordova-Plugin-HTTP: Generic request error
    com.silkimen.http.HttpRequest$HttpRequestException: java.net.MalformedURLException: no protocol: null/.well-known/openid-configuration
        at com.silkimen.http.HttpRequest.<init>(HttpRequest.java:1364)
        at com.silkimen.cordovahttp.CordovaHttpBase.createRequest(CordovaHttpBase.java:119)
        at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:79)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.MalformedURLException: no protocol: **null**/.well-known/openid-configuration
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:498)
        at java.net.URL.<init>(URL.java:447)
        at com.silkimen.http.HttpRequest.<init>(HttpRequest.java:1362)
```

Getting "null" instead of my IAuthConfig -> identity_server when making a request to my server. Working very well on WEB.

**Comment by wi3land** [comment]
are you trying to use the cordova http handler with the capacitor project?

**Comment by asad77** [comment]
No, i am not, i have this :
  ```
import {
  AuthActions,
  Browser,
  IAuthAction,
  IonicAuth
} from 'ionic-appauth';
import { Requestor, StorageBackend, TokenResponse } from '@openid/appauth';
import { AppUrlOpen, Plugins } from '@capacitor/core';
import { Injectable, NgZone, Output } from '@angular/core';
import { NavController, Platform } from '@ionic/angular';

constructor(
    requestor: Requestor,
    storage: StorageBackend,
    browser: Browser,
    private platform: Platform,
    private ngZone: NgZone
  ) {
    super(browser, storage, requestor);

    this.addConfig();
  }
```

**Comment by mraible** [comment]
I tried these changes out in [OktaDev Schematics](https://github.com/oktadeveloper/schematics/pull/253). I found that I had to add `cordova-plugin-safariviewcontroller` for Capacitor with iOS. Without it, I see the following in my Xcode logs:

```
⚡️  TO JS {}
To Native Cordova ->  SecureStorage get SecureStorage191186130 ["options": [SecretStore, token_response]]
⚡️  To Native ->  App addListener 87187584
2020-02-25 15:27:47.793389-0700 App[70227:8172686] [Accessibility] WKContentView[@] set up: @ pid: @ MACH_PORT -8323584
To Native Cordova ->  CordovaHttpPlugin get CordovaHttpPlugin191186131 ["options": [https://dev-133320.okta.com/oauth2/default/.well-known/openid-configuration, {
    Cookie = "JSESSIONID=E1DFC4A69FA7914C520E47E69FB70713";
}, 60, 1, text]]
To Native Cordova ->  SecureStorage init SecureStorage191186132 ["options": [SecretStore, {
}]]
To Native Cordova ->  SecureStorage init SecureStorage191186133 ["options": [SecretStore, {
}]]
⚡️  [warn] - Native: tried calling SafariViewController.isAvailable, but the SafariViewController plugin is not installed.
⚡️  [warn] - Install the SafariViewController plugin: 'ionic cordova plugin add cordova-plugin-safariviewcontroller'
⚡️  [error] - Sign in error: plugin_not_installed
```

NOTE: I'm using the CordovaHttpPlugin because of a [previous discussion](https://github.com/wi3land/ionic-appauth-capacitor-demo/issues/2#issuecomment-484848727).

Unfortunately, this causes an error (but not a failure) for Android.

```
✖ copy: ENOENT: no such file or directory, open '.../ionic-capacitor/android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml'
[error] [Error: ENOENT: no such file or directory, open '.../ionic-capacitor/android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.../ionic-capacitor/android/capacitor-cordova-android-plugins/src/main/AndroidManifest.xml'
}
✔ Updating Android plugins in 20.99ms
  Found 0 Capacitor plugins for android:
  Found 4 Cordova plugins for android
    cordova-plugin-advanced-http (2.4.1)
    cordova-plugin-file (6.0.2)
    cordova-plugin-secure-storage (3.0.2)
    cordova-plugin-safariviewcontroller (1.6.0)
✔ update android in 79.88ms
```

I'm not sure if it'd be better to tell people they need to install the `safariviewcontroller` or show the error for Android and tell them to ignore it.

FWIW, I tested everything on iOS and Android with Okta and it all works!

**Comment by wi3land** [comment]
@asad77 is this still an issue for you? i set my capacitor environment in an attempt to try and get the same error and couldn't see it in the log cat. 

I saw [this](https://github.com/wi3land/ionic-appauth/issues/13#issuecomment-590987805) from you but it might be helpful to see your services to see what your factory is doing.

```
import { storageFactory } from './factories';
import { NgHttpService } from './ng-http.service';

@NgModule({
  imports: [
    CommonModule
  ],
  providers: [
    {
      provide: StorageBackend,
      useFactory: storageFactory,
      deps: [Platform]
    },
    {
      provide: Requestor,
      useClass: NgHttpService
    },
    {
      provide: Browser,
      useClass: CapacitorBrowser
    }
  ]
})
export class CoreModule { }
```
The NgHttpService is the one service for angular default, however if the CordovaRequestor is here then it will attempt to use the cordova-advanced-http.

**Comment by wi3land** [comment]
I am going to close down this problem due to no reply. If you wish to continue this issue open it back up.
