### ISSUE TITLE
How to redirect to a specific view after logging in?

### ISSUE THREAD

**Issue by sneko** [wi3land/ionic-appauth#15]
Hi @wi3land ,

For a specific application I could have a "sign in" button at different places and I would like to know what is the best way to remember the "current view" so that after a successful login that redirects the user on the callback URL, I would be able to redirect the user to the "saved view".

I saw the `loginHint` parameter that allow adding some info:
https://github.com/wi3land/ionic-appauth/blob/master/src/ionic-auth.ts#L225-L228

but I'm not sure this is the right thing to use. What do you think?

Thank you,

**Comment by wi3land** [comment]
It kind of falls outside the actual project but I have done something like this myself.
I would just save the current location to local storage after the sign in button is clicked. 
Once the authentication is completed pull the item out of local storage and navigate using the angular router.

You can use the onSignInSuccessful(action: IAuthAction) method in IonicAuth to wait a successful sign in result to redirect on or subscribe to the authObserver and wait for the SignInSuccess action.

**Comment by sneko** [comment]
Yeah it could be a solution :) 

Otherwise maybe we could allow setting a state as explained here https://auth0.com/docs/protocols/oauth2/oauth-state

This one is passed back inside the callback url so I would be able to parse the stringified JSON to see some none-sensitive information. WDYT?

BTW, I'm not sure to understand the purpose of "login_hint" passed into extras property?

**Comment by wi3land** [comment]
login_hint, is a parameter to pass a username/email to the login prompt if your storing who was previously logged in.

Its definitely possible, I wouldn't be able to look into building this myself for a while. 
If you want to build it in then your welcome to fork the code and send a pull request when you have the solution and ill review it and commit to the library.

**Comment by sneko** [comment]
Thank you for the answer @wi3land !

I'm just discovering the world of OpenID Connect / OAuth2, I need to finish all implementation needed on my side but if I end up implementing this in my project I will for sure contribute to the repo!

Great lib' BTW 👍

**Comment by sneko** [comment]
Hi @wi3land , 

Any plan to implement it?

From what I understand, the state should just be passed to this object:
https://github.com/wi3land/ionic-appauth/blob/6c097aab214b7b89d17db4d4f03a02d128a2e10a/src/auth-service.ts#L144-L150

according to https://github.com/openid/AppAuth-JS/blob/a8c2962d7a24010ec1b4eb0e6eb3a9b0234f5733/src/authorization_request_test.ts#L25-L32

No?

My only doubt is about the current behavior, even if I cannot specify one with IonicAppAuth, a random one is generated, so I guess I should handle the randomness on my own if I was populating one?
