### ISSUE TITLE
Conflict of events at startup

### ISSUE THREAD

**Issue by sneko** [wi3land/ionic-appauth#18]

**Comment by sneko** [comment]
(sorry for the empty message, clicked enter...)

Hi @wi3land ,

I encountering an issue during the AuthorizationCallback and initialization of the module. Indeed `startUpAsync()` will register listeners to be aware of events like login/logout...

Except that if I try to handle a callback before, the code will end up into:
https://github.com/wi3land/ionic-appauth/blob/53e6d873896a859b56c9a4362ef0e4e292bb8149/src/ionic-auth.ts#L167-L177

And if you take a look closer you can see at lines 172 and 175 there is no `await`. It means the process will continue.

So in my case if I do:
```
await auth.handleCallback(url)
await auth.startUpAsync()
```

the `startUpAsync()` will be called even if the handling of callback if not finished. It causes an issue before `startUpAsync()` starts listening events, and then check tokens.

In this case, I will receive 2 events:
- the first one, from `startUpAsync` telling there is no token (failure)
- the second one from the callback handling telling there is a valid token (success)

I'm wondering if you could add the 2 needed `await` so no listeners will be set up before the callback handling is finished?

Thank you,

**Comment by wi3land** [comment]
do you want it to look like this

```
public async AuthorizationCallBack(url: string){
        this.browser.closeWindow();
       
        if(this.requestHandler instanceof AuthorizationRequestHandler){  
            await this.storage.setItem(AUTHORIZATION_RESPONSE_KEY, url);
            return this.requestHandler.completeAuthorizationRequestIfPossible();
        }else{
            await this.storage.setItem(IMPLICIT_RESPONSE_KEY, url);
            return this.requestHandler.completeImplicitRequestIfPossible();
        } 
    }
```

**Comment by sneko** [comment]
Since they both return `Promise<void>` I have no preference, either what you wrote or:
```
    public async AuthorizationCallBack(url: string){
        this.browser.closeWindow();
       
        if(this.requestHandler instanceof AuthorizationRequestHandler){  
            await this.storage.setItem(AUTHORIZATION_RESPONSE_KEY, url);
            await this.requestHandler.completeAuthorizationRequestIfPossible();
        }else{
            await this.storage.setItem(IMPLICIT_RESPONSE_KEY, url);
            await this.requestHandler.completeImplicitRequestIfPossible();
        } 
    }
```

Thanks for taking this into account! I think it will help people "blocking" the first page showing to route either onto a account view or an onboarding view.

**Comment by wi3land** [comment]
Take 0.5.1 for the fix

**Comment by sneko** [comment]
Oh... it doesn't fix the issue.

https://github.com/openid/AppAuth-JS/blob/a8c2962d7a24010ec1b4eb0e6eb3a9b0234f5733/src/authorization_request_handler.ts#L126-L133

Since they do `.then()` all "upper" await get unblocked and the notifier has not been called.

I need to find another way to bypass this behavior.

Maybe by doing:
- If I get into the callback handling, to route I need to wait for 2 events instead of 1
- I ignore the one whose the action name is either `AuthActions.AutoSignInFailed` or `AuthActions.AutoSignInFailed` (since it's coming from the `startupAsync()` and does not reflect the truth since executed too early before callback handling is fully finished)
- I process the other one as the real one

Otherwise I could make a child class to override the behavior of events spreaded without blocking.

Sounds overhead in all cases haha... If you have an idea on this, I take 👍

**Comment by wi3land** [comment]
yeah, the whole reason the observable exists in the background of the library to pump out actions is because there is no way to track the code as it relies on a listener and a notifier which breaks the await chain. 

Can you explain a bit what your trying to achieve and i will try and have a think about a solution.

**Comment by sneko** [comment]
@wi3land my main issue as explained above is that if I handle the callback before the `startupAsync()` I would receive 2 events and I would be unable to determine which one is the wanted one.

This is due to `await` not fully blocking until the first callback event is sent. It means that without a manual "await sleep(...)", the `startupAsync()` will start listening and also trigger an login event.

Having 2 events is problematic because I'm in an application, and before routing for the first time I want to know if the user is logged in or not. (and so receiving 2 events (failure/failure) or (failure/success) is problematic since some logic of routing is in inside the listeners).

I made a workaround to handle this overlap of events:

Application.vue / mounted():
```
    // Initialize the Authentication service that manage OpenID Connect flow
    const handledCallback = this.$authService.init(requestedUrl);
    if (handledCallback !== null) {
      switch (+handledCallback) { // The "+" is to hack a typescript issue (https://stackoverflow.com/questions/27747437/typescript-enum-switch-not-working)
        case AuthenticationCallback.AuthorizationCallBack:
          urlPathname = '/account';
          break;
        case AuthenticationCallback.EndSessionCallBack:
          urlPathname = '/';
          break;
      }
    }
```

AuthenticationService.ts:
```

export enum Callback {
	AuthorizationCallBack,
	EndSessionCallBack,
};


...


  public detectCallback(requestedUrl: string): Callback | null {
    let handledCallback: Callback | null = null;

    // Check the url contains the root we want and react accordingly
    if (this.authConfig) {
      if ((requestedUrl).indexOf(this.authConfig.redirect_url) === 0){
        handledCallback = Callback.AuthorizationCallBack;
      } else if ((requestedUrl).indexOf(this.authConfig.end_session_redirect_url) === 0){
        handledCallback = Callback.EndSessionCallBack;
      }
    }

    return handledCallback;
  }

  public init(requestedUrl: string): Callback | null {
    // Before initializing, get the reference of the authentication module linked to this service events
    this.authModule = getModule(AuthModule);
    
    // [HACK] We differentiate the init depending on the callback handling due to issue https://github.com/wi3land/ionic-appauth/issues/18
    const handledCallback = this.detectCallback(requestedUrl);
    
    if (handledCallback !== null) {
      // Start listening for events
      // Note: we cast `this` as any since `authObservableEvents` method is private
      this.authObservable.subscribe((action : IAuthAction) => (this as any).authObservableEvents(action));

      // React for the according callback
      switch (+handledCallback) { // The "+" is to hack a typescript issue (https://stackoverflow.com/questions/27747437/typescript-enum-switch-not-working)
        case Callback.AuthorizationCallBack:
          this.AuthorizationCallBack(requestedUrl);
          break;
        case Callback.EndSessionCallBack:
          this.EndSessionCallBack();
          break;
        default:
          throw new Error('The callback detected is not handled');
      }
    } else {
      // Try to log in the user depending on information in the chosen storage (+ listening for events)
      super.startUpAsync();
    }
    
    // Since the `startUpAsync()` is async we use events to handle the first login attempt result
    // Note: you have to wait for it manually in your code if necessary (before routing...)
    this.initCalledOnce = true;

    return handledCallback;
  }
```

It makes things a little more complicated, but it avoids overlap of events even if a callback if triggered, and it allows me from the `Application.vue` to route depending on the callback (endsession -> logout, authorization -> account).

I hope it can help someone, if someone finds a simpler solution, do not hesitate to share (was made as quickly as possible) 👍 

Thank you for your work,
