### ISSUE TITLE
Is this maintained any more?

### ISSUE THREAD

**Issue by addahlbe** [wi3land/ionic-appauth#202]
It seems like several pull requests never get accepted and this project falls behind. I created a copy of it, along with some updates on required packages for Ionic 7. I did not update anything besides the angular demos (I don't have experience in the others). The project is here: @addahlbe/ionic-app-auth. If anyone would like to submit pull requests, I'd be more than happy to review and work on maintaining a new / current version of this project.

**Comment by mraible** [comment]
Hello @addahlbe. I have the ability to merge pull requests, but I don't have permission to publish an updated artifact to npmjs.org. I've asked @wi3land for permission in the past but haven't received any replies. Maybe I should contact npmjs.org to see if they can provide permissions?

**Comment by addahlbe** [comment]
Hey, thanks for getting back so quickly. I suppose I could have phrased my comment a little better. I appreciate you reviewing and approving pr's, but ideally I'm not pointing my project to a git repo. It not being maintained definitely falls to not being updated on npm.

 I think if npm can do something that would be great. Otherwise I'm not sure if we just fork and go from there? That is mostly what I did with the new project (I added some support for ionic 7, and removed deprecated items). I also updated the angular demo to all the latest packages / support for Ionic 7. I'm using that project in a dev environment now, and it is under testing by my team.

**Comment by richardshergold** [comment]
Thanks guys - all efforts very much appreciated. We use this package in Production and I’m starting to worry a little bit about things getting out of date and having problems down the line. We would be looking to migrate to Ionic 7 pretty soon so it would be great if this library was to support that and be maintained going forwards.

**Comment by wi3land** [comment]
Apologies everyone, I no longer work as an ionic developer and rarely look at my GitHub. 

@mraible let me know everything you need and I'll get it sorted this week

**Comment by mraible** [comment]
@wi3land It'd be great to have admin rights to this project and the ability to publish the npm package on https://www.npmjs.com.

**Comment by mraible** [comment]
@addahlbe @richardshergold I now have permission to publish this project on npmjs.com. If there's anything you'd like to contribute for Ionic 7 compatibility, that'd be awesome!

**Comment by addahlbe** [comment]
@mraible Awesome news, the changes I made should have everything working for Ionic 7. I've had a dev app pointed to the branch for 2 weeks now and my team hasn't noticed any issues. I can update the demos soon hopefully.

**Comment by mraible** [comment]
@addahlbe Sounds great! Will everything work with Ionic 6, too? 

Since CI and tests were added to fix https://github.com/wi3land/ionic-appauth/issues/138, maybe we release it as 1.0.0?

**Comment by mraible** [comment]
I tried to release 1.0.0 and ran into issues. It appears that 1.0.0 and 1.0.1 were published four years ago. Scroll down to the bottom of this page to see:

https://www.npmjs.com/package/ionic-appauth?activeTab=versions

What version do y'all think we should use? I think 1.1.0 might be good, but I'm not opposed to 2.0.0 too.

**Comment by richardshergold** [comment]
I think either would be ok. It’s great you are now sorting this. Thanks.

**Comment by wellwoller** [comment]
@mraible I think 2.0.0 would be a cleaner cut but it is up to you. Hope I can use the new version soon. 
Thanks for taking care of this

**Comment by mraible** [comment]
I agree that 2.0.0 is probably the best route. I released it this morning and will close this issue. 

https://github.com/wi3land/ionic-appauth/releases/tag/v2.0.0
