### ISSUE TITLE
@ionic-native/secure-storage is "deperacted" switch to local storage if possible

### ISSUE THREAD

**Issue by yelhouti** [wi3land/ionic-appauth#24]
@ionic-native/secure-storage or more precisely, https://github.com/Crypho/cordova-plugin-secure-storage is deprecated, we should have the option to use localstorage even if one might think that it involves security risks. I personally don't think so and we can debate it, I might be wrong.

**Comment by wi3land** [comment]
You can implement what ever storage you fancy. We have changed over to cordova-plugin-secure-storage-echo in all the demos, which still works with the Cordova storage service I built.

However you can simply implement the StorageBackend interface from @openid/appauth, to create your own storage service.

Then pass it into your IonicAuth constructor.

**Comment by wi3land** [comment]
Please reopen this issue if you need further instruction on how to implement your own storage service.
