### ISSUE TITLE
 Unable to generate PKCE challenge error only on Android

### ISSUE THREAD

**Issue by iturn** [wi3land/ionic-appauth#25]
All is working well in the browser and iOS simulator but when i install the app via de IDE on my android device i get these error bubbling up from the appAuth library, when i go to the webpage where the login needs to be done.

The error comes from here, line 86
https://github.com/openid/AppAuth-JS/blob/master/src/authorization_request.ts 

I've read that this might have to do with that the andriod browser or app is running as http instead of https which might window.crypto to be unavailable?
https://stackoverflow.com/questions/46468104/how-to-use-subtlecrypto-in-chrome-window-crypto-subtle-is-undefined 

Any ideas on this?

**Comment by iturn** [comment]
After more testing i've come to find that it was not about any for the code or packages directly. It was due to running ionic with the --external flag which made the app run under some local ip instead of localhost. This in turn caused the window.crypto to not start as localhost is a trusted source, but the random local ip isn't trusted.

**Comment by Elite40** [comment]
I see that the thread is closed, but as i'm also struggling with this issue i want to ask you something: 

How did you eventually fixed/by-passed this error?

**Comment by admin-delcom** [comment]
For development we run the app with this command; ionic capacitor run android --configuration=yourConfigOrRemoveThisForDefault

**Comment by Elite40** [comment]
And how does the configuration file look? Because i didn't heard of it before. 

Do you mean the `capacitor.config.json` file?

**Comment by admin-delcom** [comment]
`
{
  "appId": "com.corp.app",
  "appName": "Some app name",
  "bundledWebRuntime": false,
  "npmClient": "npm",
  "webDir": "www"
}
`

**Comment by Elite40** [comment]
Alright, i will give it a try. Thanks!

**Comment by StephanBis** [comment]
We seem to be at a dead end here. We need to run the command with the --external flag as we're using capacitor for native iOS and Android. Not running the app with the --external flag results in a 404 when when the app boots. Does anyone know how to fix this? We can't find another way to get PKCE running.

**Comment by philmmoore** [comment]
@StephanBis did you have any luck resolving this at all?
