### ISSUE TITLE
Support for Client Secret in Auth Code Flow For Cordova/Ionic

### ISSUE THREAD

**Issue by uncvrd** [wi3land/ionic-appauth#3]
Hi! Thanks so much for working on this Ionic implementation of AppAuth! So far so good on the web side. Unfortunately, it looks like my OpenID endpoint does not support PKCE implementation (I don't have a `code_challenge_methods_supported` section in my `.well-known/openid-configuration`)

So this looks like I will have to use my client secret to authenticate? Is using a Client Secret currently not supported by this library? I guess we would need a way to hit a server endpoint to then send the request serverside so we can add the secret (that's stored on the server) in the Auth header?

Thanks for any insight if this is possible or not!

**Comment by wi3land** [comment]
Hi, client secrets are not advised for js clients as you can never truly secure a client secret within JavaScript.

That being said you can add a secret to the auth extras property of the auth config and that will be sent over the secret as as part of the authorization/implicit request. 

I would advise that if you do plan on going down this root. You at least look into obfuscation of your app, if it ever goes to production.

**Comment by uncvrd** [comment]
I very much agree that this is not advisable. So it turns out we're currently just waiting for our auth team to finish up our openID endpoint which will support PKCE. Since this will be only for internal testing, what is the key name that I would use for adding the secret in the auth extras property? I assume something like: `client_secret` or `secret`?

**Comment by wi3land** [comment]
Client_secret I think

**Comment by uncvrd** [comment]
Thanks! I'll give that a shot :)
