### ISSUE TITLE
Vanilla Javascript Example

### ISSUE THREAD

**Issue by TensorTom** [wi3land/ionic-appauth#30]
I'm currently building an app using Capacitor and vanilla js. It's very difficult looking at this module how to use it by the ionic example. I'm wanting to authenticate against a private site with my own oauth server. A simple code snippet would do if possible. Thanks.

**Comment by mraible** [comment]
If you're not using Ionic, you might be able to use [AppAuth JS](https://github.com/openid/AppAuth-JS) directly. This library simply builds on top of it for Ionic.

**Comment by wi3land** [comment]
There is no plans at the moment to create a vanilla js example. My next demo I will work on will be Vue. If you do build a code snippet for vanilla js then please let me know and I will attach it to the project.
