### ISSUE TITLE
Should i be using deeplinks?

### ISSUE THREAD

**Issue by yehiasalam** [wi3land/ionic-appauth#31]
Hi,

Great contribution thanks, the only one that works with ionic.

I have a question regarding the InAppBrowser behavior, am i supposed to listen for the redirect_uri using the cordova or capacitor browser addListener function, or am i supposed to register universal links using cordova deeplinks plugin and the inappbrowser will relaunch the app when the url matched com.ionic.starter/callback for example.

**Comment by wi3land** [comment]
When using capacitor you will be using the [Capacitor App Plugin](https://capacitorjs.com/docs/apis/app). On Cordova you will be using [Cordova Custom Url Scheme](https://github.com/EddyVerbruggen/Custom-URL-scheme). I haven't tried using cordova deep links but when i was setting up the demos, Cordova deep links was deprecated. If you want to see how the two plugins are used above, view the [ng demo](https://github.com/wi3land/ionic-appauth-ng-demo) or the [capacitor demo](https://github.com/wi3land/ionic-appauth-capacitor-demo) for this package.

**Comment by yehiasalam** [comment]
okay thanks, i ended up using universal links with the guides you shared thanks.
