### ISSUE TITLE
What is the purpose of callbackUrl in browser showWindow interface?

### ISSUE THREAD

**Issue by ntziolis** [wi3land/ionic-appauth#48]
When looking at the browser interfaces `showWindow` show window method there is a parameter `callbackUrl`.
https://github.com/wi3land/ionic-appauth/blob/3c4c5e900ffc3549090333bd53fbff643473afc2/src/auth-browser.ts#L4

However when looking at the browser implementations for capacitor or cordova the parameter is not implemented. 
https://github.com/wi3land/ionic-appauth/blob/3c4c5e900ffc3549090333bd53fbff643473afc2/src/capacitor/capacitor-browser.ts#L14
https://github.com/wi3land/ionic-appauth/blob/3c4c5e900ffc3549090333bd53fbff643473afc2/src/cordova/cordova-browser.ts#L25

Is there a future purpose for this parameter or simply a reminiscence of previous implementations which could be removed moving forward?

**Comment by wi3land** [comment]
The original implementation is from [AppAuth-JS](https://github.com/openid/AppAuth-JS) which is specifically for browser based clients. 
As this library is built for native devices we cant call back into the callback and have to use a deep link instead. So it will never be used in this library.
