### ISSUE TITLE
Expose replay subject for isAuthenticated state

### ISSUE THREAD

**Issue by ntziolis** [wi3land/ionic-appauth#49]
It would be a very useful addition to have a subject exposed that developers can subscribe to in guards and other places in the application that depend on if a user is logged in or not.

While we were able to figure out how to get this done it wasn't straight forward and we are still not sure if this is the correct way of doing it:
```ts
    // create an chainable subject from of auth actions
    const authAction$ = new ReplaySubject<IAuthAction>();
    auth.addActionListener(authAction$.next.bind(authAction$));

    // afterwards load  token from storage   
    auth.loadTokenFromStorage();

    // use a subject to allow access from anywhere within the application and get latest state
    // in our case this is exposed as public property on our CustomAuthService
    const authenticated$ = new ReplaySubject<boolean>();

    authAction$
      .pipe(
        switchMap(() => auth.getValidToken()),
        catchError(() => of(null)),
        map((token) => !!token),
        tap((isTokenValid) => authenticated$.next(isTokenValid))
      ).subscribe();
```

We found leveraging `auth.session.authenticated` to not be reliable since the token might already be expired. In order to rely on the value one needs to make a request for a valid token first. We found that if there is a valid token, the user is authenticated, hence we are not checking `auth.session.authenticated` again after requesting a valid token.

Questions:
- Are we doing this correctly with the intended purpose in mind to have a replay subject that always returns the latest authentication state
- Do you see the appeal in exposing this directly on the auth service, if so I'm happy to create a PR

**Comment by wi3land** [comment]
I have exposed the isAuthenticated$ subject in 0.8.1, however it is a behaviour not a replay subject
