### ISSUE TITLE
Capacitor 3

### ISSUE THREAD

**Issue by anweihe** [wi3land/ionic-appauth#61]
Update this plugin for Capacitor 3. This works for me: https://github.com/anweihe/ionic-appauth/commit/ec9dcff0b085eb32a3e07de3549e33d906672864

**Comment by PhilippRoessner** [comment]
@anweihe  Is the redirect working for you? In my android app the redirect is not working after upgrading to Capacitor 3, before it was working. I am using your PR and at least build is working now.

**Comment by anweihe** [comment]
@PhilippRoessner Yes, redirect is working with Android and iOS.

**Comment by Nazirovich** [comment]
How can I install the working version of this package that works with capacitor 3 ?

**Comment by muhrifqii** [comment]
@anweihe how can I use your fork as replacement for current project's npm package?

**Comment by wi3land** [comment]
Hi I have updated to capacitor 3 please take version 0.8.0
