### ISSUE TITLE
CapacitorBrowser displays native browser Header and Footer(Safari[iOS]/Chrome[Android])

### ISSUE THREAD

**Issue by dipankarmedhi91** [wi3land/ionic-appauth#64]
Followed the pattern described here to use ionic-appauth : https://github.com/wi3land/ionic-appauth-react-demo

When the App redirects to OAuth pages, it is showing up the Browser Header and Footers, which leads to a bad user experience
Is there a way to hide them? or any other browser plugin I should try out?
PFA screenshot in iPhone: 
See the header and footer in Red Outlined boxes

<img width="381" alt="Issue" src="https://user-images.githubusercontent.com/10825788/124692391-878ef900-deab-11eb-8670-60e1d99e4170.png">

**Comment by wi3land** [comment]
It is important to show the top bar so the user knows where they are being redirected to.
This project is just using the [Capacitor Browser](https://capacitorjs.com/docs/apis/browser).
So whatever they provide is what is provided in the project.
