### ISSUE TITLE
Implicit flow not supported in ionic-appauth

### ISSUE THREAD

**Issue by dipankarmedhi91** [wi3land/ionic-appauth#67]
According to the comment here: https://github.com/openid/AppAuth-JS/issues/25#issuecomment-481666961
but seems like implicit flow is not supported

**Comment by wi3land** [comment]
Apologies implicit flow did use to exist in this library a few years ago. however it was removed as it isn't really a recommended for oauth on mobile. Also the implementation was quite hollow with no check session implementation.

If you look on the previous commits you can see where it is removed and implement it as it was back then. but unless there is a huge call for this to be added again. It will remain removed.

**Comment by dipankarmedhi91** [comment]
@wi3land Thanks for the information
