### ISSUE TITLE
I think something broke with getValidToken in your last commit

### ISSUE THREAD

**Issue by AndrWeisR** [wi3land/ionic-appauth#7]
getValidToken() in ionic-auth.ts doesn't seem to return a token any more. It looks for a token in this.authSession.token, but I'm getting that as undefined, after a successful auto-sign in. In startUpAsync(), you get a stored token from storage and you then feed it into authSubject, but this.authSession.token isn't updated, is it?

Or do I need to pass an authSession in to the IonicAuth constructor now?

If I override getValidToken in my own IonicAuth subclass, and revert the code to use getTokenFromObserver again, then everything works again:
`let token: TokenResponse | undefined = await this.getTokenFromObserver();`

**Comment by wi3land** [comment]
Apologies, the auth session was a test setup for building react. 
I have removed it as i don't really think it has a place in the package and should be more of an implementation feature when creating an app. I have set it back to how it was originally.
