### ISSUE TITLE
ionic-appauth 0.8.1 Requires @ionic/storage@3.0.6 To Run npm CI builds 

### ISSUE THREAD

**Issue by mrogunlana** [wi3land/ionic-appauth#78]
This isn't a bug per se, but will help those of us using continuous integration processes to deploy ionic applications that use the latest ionic-appauth package.

Steps to reproduce:
1. Install ionic-appauth 0.8.1 via npm
2. `run npm ci --quiet --no-optional`
3. `ionic build --prod`
4. the following error will appear: 
```
./node_modules/ionic-appauth/lib/auth-storage.js:2:0-41 - Error: Module not found: Error: Can't resolve '@ionic/storage' in 'c:\Projects\Iak\ionic-development\node_modules\ionic-appauth\lib'

Error: node_modules/ionic-appauth/lib/auth-storage.d.ts:2:25 - error TS2307: Cannot find module '@ionic/storage' or its corresponding type declarations.

2 import { Storage } from '@ionic/storage';
                          ~~~~~~~~~~~~~~~~
```

in order to fix this exception, in new installations, install the following package and save it as a dependency like so: `npm i @ionic/storage@3.0.6 --save`

hopefully this will save someone a few hours of headache :)

it would be nice if the readme of this project contained required package dependencies to help curb these one off package related issues moving forward; does anyone agree?

**Comment by mraible** [comment]
@ionic/storage is listed as an optional dependency in this libraries'
`package.json`. Maybe it should be a peer dependency so npm v7+ pulls it in
by default?

**Comment by mraible** [comment]
Can you please try the latest code on the main branch to see if it solves this for you?

```json
"ionic-appauth": "github:wi3land/ionic-appauth",
```

**Comment by mraible** [comment]
Closing due to no response. Please re-open if the latest code on the main branch doesn't work for you.

**Comment by Ajax-ua** [comment]
The same issue trying to deploy Ionic app with latest ionic-appauth v2.0.0 package using Appflow with the latest build stack. 
FYI, locally the app is built successfully. For me the problem persists only on Appflow

**Comment by aishwarya-symplr** [comment]
> The same issue trying to deploy Ionic app with latest ionic-appauth v2.0.0 package using Appflow with the latest build stack. FYI, locally the app is built successfully. For me the problem persists only on Appflow

after that ios production app is not working
