### ISSUE TITLE
React Example - status?

### ISSUE THREAD

**Issue by mpkelly** [wi3land/ionic-appauth#8]
Hi, 

How far along is the [React/Capacitor example](https://github.com/wi3land/ionic-appauth-react-demo)? It looks fairly complete to me but after importing the example files and running my app I get a blank screen but no error is logged. It seems like `<AppAuthProvider>` becomes a black hole that swallows up its children and never renders anything. 

Can someone please confirm the current status?

**Comment by wi3land** [comment]
Hi Sorry, For the late reply. 
Sadly I am not a react developer, so I was kind of just trying my best to get a working example together. I am currently quiet busy so have no time to spend on the example at the moment.
Please feel free to have a go yourself.

I have expanded the ionic app auth library to no longer rely on rxjs and have event handlers instead so it can work better with react. I did get it to a point where it worked on web but for some reason had issue on mobile.

**Comment by sneko** [comment]
Hi @wi3land , not fully related but when cloning your repo and running `yarn run start` I just see `Awaiting Auth` in my browser.

That's due to `authAction.action !== AuthActions.Default` but I don't understand what's need to be done to try your example. Is it compatible while running it on a desktop? Or do I have to make it running in a full capacitor app on device?

Thank you,

**Comment by wi3land** [comment]
I'm not going to lie to you, the example is pretty busted. I built it when I had 5 days spare and was learning react as I was going. I did have it working in browser at one point but I think I broke it when I was making it work for mobile. 

The only reason. It is up, is in the hopes that someone with good knowledge of react can take it over and fix my issues.

**Comment by wi3land** [comment]
Just a quick note, I spent the past few days building the react demo. i think i have it doing everything that the ng and capacitor demos do.
