### ISSUE TITLE
Capacitor 3 Deep Links lead to Sign Out

### ISSUE THREAD

**Issue by wrzr123** [wi3land/ionic-appauth#89]
Hey,

I'm developing an Ionic 6 app with Capacitor 3 and Ionic Appauth. I now integrated [Cpacitors Deep Link pattern](https://capacitorjs.com/docs/guides/deep-links) which generally works fine.

I'm starting to test now on my Android phone, and when I open my app through an Android App Link, the very first thing that happens is a Sign Out event (in the logs I see {action: 'Sign Out Success'} produced by Ionic Appauth). I have no idea what's triggering the sign out.
My app then starts a re-login process automatically, but still it's annoying for the user as it takes unnecessary time and in some cases he/she also has to enter the login credentials again. 

Does anybody know how to suppress that? I didn't try yet with a fresh app using the demo from the repo here, that would be my next try if nobody has an idea.

Thanks in advance!

**Comment by wrzr123** [comment]
Found it!

I more or less adopted the capacitor demo 1:1 in my app. This includes the auth.factory under app/core/factories. And this has the following code block;

```
if (platform.is('capacitor')) {
        App.addListener('appUrlOpen', (data: any) => {
            if (data.url !== undefined) {
                ngZone.run(() => {
                    if ((data.url).indexOf(authService.authConfig.redirect_url) === 0) {
                        authService.authorizationCallback(data.url);
                    }else{
                        authService.endSessionCallback();
                    }
                });
            }
        });
    }
```

Which calls the end session callback when the app is opened with every link except the redirect uri which is called after successful login.
I just changed it to

```
if (platform.is('capacitor')) {
        App.addListener('appUrlOpen', (data: any) => {
            if (data.url !== undefined) {
                ngZone.run(() => {
                    if ((data.url).indexOf(authService.authConfig.redirect_url) === 0) {
                        authService.authorizationCallback(data.url);
                    }else if ((data.url).indexOf(authService.authConfig.end_session_redirect_url) === 0){
                        authService.endSessionCallback();
                    }
                });
            }
        });
    }
```
And now it works like a charm! Hope this helps other people in the future. Maybe it would also make sense to adopt the demo accordingly.

**Comment by metalsho** [comment]
Form me it was another issue. The return url adds, I don't know why, 2 slash before "callback".

My workaround is this: 

environment.oidcConfig.redirect_url = `${environment.scheme}:///callback`;
