### ISSUE TITLE
Too frequent token refreshing

### ISSUE THREAD

**Issue by bartdeveloper** [wi3land/ionic-appauth#9]
In my case, ionic-appauth plugin send request for new access/refresh token to Azure AD after few/over a dozen request with bearer token (and then unfortunately Azure blocking my next requests for login for some time). Maybe it is problem with usage SecureStorage? I thought app lost entry from SecureStorage oraz my config is bad.

And another related case - when I testing solution in web browser - then I getting info: token is valid (from isValid() method), but when I testing authorization on mobile device (use Pkce: true) then I always got info: token is not valid ( isValid() return false). What might be caused this problem?

It's my config for mobile:

>        identity_client: 'id-from-Azure', 
>         identity_server: 'https://login.microsoftonline.com/some-id-graph/', 
>         redirect_url: 'APP-ID://callback',
>         scopes: 'openid profile offline_access',
>         usePkce: true,
>         end_session_redirect_url: 'APP-ID://endSession',
>         auth_extras: { 'resource' : 'api-id-from-Azure' }

**Comment by wi3land** [comment]
Hi @bartdeveloper, The ionic app auth library does the refresh when calling the getValidToken method.
It checks against the current token in the observer and calls the isValid method on that token. If its not valid it will contact the refresh endpoint. The isValid method just looks inside the current token to make sure the current date is greater than the expiry date set on the token by the server. 

I would say it could be your server config setting the expiry timeout to low. One way to check this is to copy your token onto jwt.io it will convert the expiry date into a datetime and you can see if it is getting set too low.

**Comment by bartdeveloper** [comment]
Thanks @wi3land  for reply. For example now I got token with that parameters:
issued_at: 1575371455,
expires_in: 3600
buffer valid default (-600).

and current time from _Math.round(new Date().getTime() / 1000)_ is _1575371456_ and... I got false from isValid() method (only on mobile device with pkce, when I use preview in web browser, then is OK, valid).

**Comment by AndrWeisR** [comment]
How are you configuring your own custom AUTH_EXPIRY_BUFFER? Do you have code like:

`this.authConfig.auth_extras['isValidBuffer'] = '-300';`

or

`auth_extras: { 'resource' : 'api-id-from-Azure', 'isValidBuffer' : '-300' }`

**Comment by bartdeveloper** [comment]
@AndrWeisR it is my config for mobile:
```
    identity_client: 'id-from-Azure', 
    identity_server: 'https://login.microsoftonline.com/some-id-sts/', 
    redirect_url: 'APP-ID://callback',
    scopes: 'openid profile offline_access',
    usePkce: true,
    end_session_redirect_url: 'APP-ID://endSession',
    auth_extras: { 'resource' : 'api-id-from-Azure', 'isValidBuffer' : '-300'  }
```

I am very surprised why **isValid()** return _true_ when I run app from browser and return _false_ when I run on mobile device (with Android 9) despite according to computing should return true.

**Comment by AndrWeisR** [comment]
It might be worth checking the values in the mobile app: now, this.issuedAt, expiresIn etc. Maybe one of them has a surprising value on the mobile, different to in the browser.

**Comment by bartdeveloper** [comment]
Data in browser:
![browser](https://user-images.githubusercontent.com/44911371/70114887-4c3ca080-165e-11ea-8871-99280c1210f6.PNG)
Data in mobile:
![mobile](https://user-images.githubusercontent.com/44911371/70114888-4c3ca080-165e-11ea-90fb-1201a75eaf4c.PNG)
Browser token (jwt.io):
![token-browser](https://user-images.githubusercontent.com/44911371/70114890-4c3ca080-165e-11ea-8341-3504042bba1a.PNG)
Mobile token (jwt.io):
![token-mobile](https://user-images.githubusercontent.com/44911371/70114891-4cd53700-165e-11ea-86cd-ab57a79d50db.PNG)

**Comment by bartdeveloper** [comment]
Guys, I found solution/bug - it is in openid/AppAuth-JS library. Browser on my mobile treats _expiresIn_ value as string so I have to convert it to number using Number() function and then _isValid()_ method return true.
My pull request: https://github.com/openid/AppAuth-JS/pull/132

**Comment by jeswin-roma** [comment]
Hi @bartdeveloper - I am facing an issue where the Azure Active Directory users are kicked out of the Ionic/Angular app after 24 hours (I use bearer token and not refresh token). Can you please share how you implemented the refresh token to keep the login session always active? I tried looking around for plugins but couldn't find any - other than Auth Connect which needs an enterprise license. Thanks.

**Comment by mraible** [comment]
I've used refresh tokens with this library and Okta successfully. The most important thing is to include "offline_access" in your scopes.
